project:
  type: website

website:
  title: "Cophy Project"
  navbar:
    background: dark
    left:
      - text: "Get started"
        file: getstarted.qmd
      - text: "Tutorial"
        file: tutorial.qmd        
      - text: "About"
        file: about.qmd

format:
  html:
    theme: 
      - cerulean
      - custom.scss
    toc: true